### ISSUE TITLE
Support negated `\P{…}` form?

### ISSUE THREAD

**Issue by mathiasbynens** [mathiasbynens/proposal-regexp-unicode-sequence-properties#6]
https://github.com/mathiasbynens/proposal-regexp-unicode-sequence-properties/commit/c21ef13457a725da36b6feb75778b06967aaaf32 removed this from the explainer.

Does `\P{UnicodeSequenceProperty}` make sense? We could make it desugar into a negative lookahead, but would that be useful?

**Comment by hashseed** [comment]
I agree. `\P` would lead to confusion, since it's not clear how long the sequence may be.

E.g. `/\P{UnicodeSequenceProperty}./` used on an unicode sequence would likely match because it would consume part of the sequence and then the remaining character.

I'd rather have people use negative lookahead explicitly.

**Comment by mathiasbynens** [comment]
https://github.com/mathiasbynens/proposal-regexp-unicode-sequence-properties#high-level-api
